version: 0.2

phases:
  build:
    commands:
#      - aws s3 rm --recursive s3://$WEBSITE_S3_BUCKET/public/
      - aws s3 cp --recursive build/ s3://$WEBSITE_S3_BUCKET/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - sed -i -e "s|/static/|$WEBSITE_S3_PREFIX/public/static/|g" build/index.html
#      - sed -i -e "s|/manifest.json|$WEBSITE_S3_PREFIX/public/manifest.json|g" build/index.html
      - sed -i -e "s|/icon.png|$WEBSITE_S3_PREFIX/public/icon.png|g" build/manifest.json
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml


